# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

runGibbs <- function(model, data_, numIter, burnIn, warmup, thin, numComponents = -1L, log_every = 100L, usePseudoPrior = FALSE) {
    .Call(`_SemiHDP_runGibbs`, model, data_, numIter, burnIn, warmup, thin, numComponents, log_every, usePseudoPrior)
}

predictiveSamples <- function(model, chains) {
    .Call(`_SemiHDP_predictiveSamples`, model, chains)
}

runNormalConjugateGibbs <- function(data_, numIter, burnIn, warmup, thin, numComponents, log_every, usePseudoPrior) {
    .Call(`_SemiHDP_runNormalConjugateGibbs`, data_, numIter, burnIn, warmup, thin, numComponents, log_every, usePseudoPrior)
}

runSemiHdpBlockedGibbs <- function(data_, numIter, burnIn, warmup, thin, numComponents, log_every, usePseudoPrior) {
    .Call(`_SemiHDP_runSemiHdpBlockedGibbs`, data_, numIter, burnIn, warmup, thin, numComponents, log_every, usePseudoPrior)
}

runSemiHdpMarginal <- function(data_, numIter, burnIn, warmup, thin, log_every, usePseudoPrior) {
    .Call(`_SemiHDP_runSemiHdpMarginal`, data_, numIter, burnIn, warmup, thin, log_every, usePseudoPrior)
}

