# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chain_state.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chain_state.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x11\x63hain_state.proto\"\x18\n\x07Par_Col\x12\r\n\x05\x65lems\x18\x01 \x03(\x01\"#\n\x05Param\x12\x1a\n\x08par_cols\x18\x01 \x03(\x0b\x32\x08.Par_Col\"&\n\x0cUniqueValues\x12\x16\n\x06params\x18\x01 \x03(\x0b\x32\x06.Param\"A\n\x05State\x12\x13\n\x0b\x61llocations\x18\x01 \x03(\x05\x12#\n\x0cuniquevalues\x18\x02 \x03(\x0b\x32\r.UniqueValuesb\x06proto3'
)




_PAR_COL = _descriptor.Descriptor(
  name='Par_Col',
  full_name='Par_Col',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='elems', full_name='Par_Col.elems', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=45,
)


_PARAM = _descriptor.Descriptor(
  name='Param',
  full_name='Param',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='par_cols', full_name='Param.par_cols', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=82,
)


_UNIQUEVALUES = _descriptor.Descriptor(
  name='UniqueValues',
  full_name='UniqueValues',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='params', full_name='UniqueValues.params', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=122,
)


_STATE = _descriptor.Descriptor(
  name='State',
  full_name='State',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='allocations', full_name='State.allocations', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uniquevalues', full_name='State.uniquevalues', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=189,
)

_PARAM.fields_by_name['par_cols'].message_type = _PAR_COL
_UNIQUEVALUES.fields_by_name['params'].message_type = _PARAM
_STATE.fields_by_name['uniquevalues'].message_type = _UNIQUEVALUES
DESCRIPTOR.message_types_by_name['Par_Col'] = _PAR_COL
DESCRIPTOR.message_types_by_name['Param'] = _PARAM
DESCRIPTOR.message_types_by_name['UniqueValues'] = _UNIQUEVALUES
DESCRIPTOR.message_types_by_name['State'] = _STATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Par_Col = _reflection.GeneratedProtocolMessageType('Par_Col', (_message.Message,), {
  'DESCRIPTOR' : _PAR_COL,
  '__module__' : 'chain_state_pb2'
  # @@protoc_insertion_point(class_scope:Par_Col)
  })
_sym_db.RegisterMessage(Par_Col)

Param = _reflection.GeneratedProtocolMessageType('Param', (_message.Message,), {
  'DESCRIPTOR' : _PARAM,
  '__module__' : 'chain_state_pb2'
  # @@protoc_insertion_point(class_scope:Param)
  })
_sym_db.RegisterMessage(Param)

UniqueValues = _reflection.GeneratedProtocolMessageType('UniqueValues', (_message.Message,), {
  'DESCRIPTOR' : _UNIQUEVALUES,
  '__module__' : 'chain_state_pb2'
  # @@protoc_insertion_point(class_scope:UniqueValues)
  })
_sym_db.RegisterMessage(UniqueValues)

State = _reflection.GeneratedProtocolMessageType('State', (_message.Message,), {
  'DESCRIPTOR' : _STATE,
  '__module__' : 'chain_state_pb2'
  # @@protoc_insertion_point(class_scope:State)
  })
_sym_db.RegisterMessage(State)


# @@protoc_insertion_point(module_scope)
