// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: output.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_output_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_output_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_output_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_output_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_output_2eproto;
class ChainOutput;
class ChainOutputDefaultTypeInternal;
extern ChainOutputDefaultTypeInternal _ChainOutput_default_instance_;
class IterationOutput;
class IterationOutputDefaultTypeInternal;
extern IterationOutputDefaultTypeInternal _IterationOutput_default_instance_;
class Par_Row;
class Par_RowDefaultTypeInternal;
extern Par_RowDefaultTypeInternal _Par_Row_default_instance_;
class Param;
class ParamDefaultTypeInternal;
extern ParamDefaultTypeInternal _Param_default_instance_;
class UniqueValues;
class UniqueValuesDefaultTypeInternal;
extern UniqueValuesDefaultTypeInternal _UniqueValues_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::ChainOutput* Arena::CreateMaybeMessage<::ChainOutput>(Arena*);
template<> ::IterationOutput* Arena::CreateMaybeMessage<::IterationOutput>(Arena*);
template<> ::Par_Row* Arena::CreateMaybeMessage<::Par_Row>(Arena*);
template<> ::Param* Arena::CreateMaybeMessage<::Param>(Arena*);
template<> ::UniqueValues* Arena::CreateMaybeMessage<::UniqueValues>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class Par_Row :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Par_Row) */ {
 public:
  Par_Row();
  virtual ~Par_Row();

  Par_Row(const Par_Row& from);
  Par_Row(Par_Row&& from) noexcept
    : Par_Row() {
    *this = ::std::move(from);
  }

  inline Par_Row& operator=(const Par_Row& from) {
    CopyFrom(from);
    return *this;
  }
  inline Par_Row& operator=(Par_Row&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Par_Row& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Par_Row* internal_default_instance() {
    return reinterpret_cast<const Par_Row*>(
               &_Par_Row_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Par_Row& a, Par_Row& b) {
    a.Swap(&b);
  }
  inline void Swap(Par_Row* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Par_Row* New() const final {
    return CreateMaybeMessage<Par_Row>(nullptr);
  }

  Par_Row* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Par_Row>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Par_Row& from);
  void MergeFrom(const Par_Row& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Par_Row* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Par_Row";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_output_2eproto);
    return ::descriptor_table_output_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kElemsFieldNumber = 1,
  };
  // repeated double elems = 1;
  int elems_size() const;
  private:
  int _internal_elems_size() const;
  public:
  void clear_elems();
  private:
  double _internal_elems(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      _internal_elems() const;
  void _internal_add_elems(double value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      _internal_mutable_elems();
  public:
  double elems(int index) const;
  void set_elems(int index, double value);
  void add_elems(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      elems() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      mutable_elems();

  // @@protoc_insertion_point(class_scope:Par_Row)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > elems_;
  mutable std::atomic<int> _elems_cached_byte_size_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_output_2eproto;
};
// -------------------------------------------------------------------

class Param :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Param) */ {
 public:
  Param();
  virtual ~Param();

  Param(const Param& from);
  Param(Param&& from) noexcept
    : Param() {
    *this = ::std::move(from);
  }

  inline Param& operator=(const Param& from) {
    CopyFrom(from);
    return *this;
  }
  inline Param& operator=(Param&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Param& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Param* internal_default_instance() {
    return reinterpret_cast<const Param*>(
               &_Param_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Param& a, Param& b) {
    a.Swap(&b);
  }
  inline void Swap(Param* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Param* New() const final {
    return CreateMaybeMessage<Param>(nullptr);
  }

  Param* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Param>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Param& from);
  void MergeFrom(const Param& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Param* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Param";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_output_2eproto);
    return ::descriptor_table_output_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kParRowsFieldNumber = 1,
  };
  // repeated .Par_Row par_rows = 1;
  int par_rows_size() const;
  private:
  int _internal_par_rows_size() const;
  public:
  void clear_par_rows();
  ::Par_Row* mutable_par_rows(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Par_Row >*
      mutable_par_rows();
  private:
  const ::Par_Row& _internal_par_rows(int index) const;
  ::Par_Row* _internal_add_par_rows();
  public:
  const ::Par_Row& par_rows(int index) const;
  ::Par_Row* add_par_rows();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Par_Row >&
      par_rows() const;

  // @@protoc_insertion_point(class_scope:Param)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Par_Row > par_rows_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_output_2eproto;
};
// -------------------------------------------------------------------

class UniqueValues :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:UniqueValues) */ {
 public:
  UniqueValues();
  virtual ~UniqueValues();

  UniqueValues(const UniqueValues& from);
  UniqueValues(UniqueValues&& from) noexcept
    : UniqueValues() {
    *this = ::std::move(from);
  }

  inline UniqueValues& operator=(const UniqueValues& from) {
    CopyFrom(from);
    return *this;
  }
  inline UniqueValues& operator=(UniqueValues&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const UniqueValues& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UniqueValues* internal_default_instance() {
    return reinterpret_cast<const UniqueValues*>(
               &_UniqueValues_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(UniqueValues& a, UniqueValues& b) {
    a.Swap(&b);
  }
  inline void Swap(UniqueValues* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline UniqueValues* New() const final {
    return CreateMaybeMessage<UniqueValues>(nullptr);
  }

  UniqueValues* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<UniqueValues>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const UniqueValues& from);
  void MergeFrom(const UniqueValues& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UniqueValues* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "UniqueValues";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_output_2eproto);
    return ::descriptor_table_output_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kParamsFieldNumber = 1,
  };
  // repeated .Param params = 1;
  int params_size() const;
  private:
  int _internal_params_size() const;
  public:
  void clear_params();
  ::Param* mutable_params(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Param >*
      mutable_params();
  private:
  const ::Param& _internal_params(int index) const;
  ::Param* _internal_add_params();
  public:
  const ::Param& params(int index) const;
  ::Param* add_params();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Param >&
      params() const;

  // @@protoc_insertion_point(class_scope:UniqueValues)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Param > params_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_output_2eproto;
};
// -------------------------------------------------------------------

class IterationOutput :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:IterationOutput) */ {
 public:
  IterationOutput();
  virtual ~IterationOutput();

  IterationOutput(const IterationOutput& from);
  IterationOutput(IterationOutput&& from) noexcept
    : IterationOutput() {
    *this = ::std::move(from);
  }

  inline IterationOutput& operator=(const IterationOutput& from) {
    CopyFrom(from);
    return *this;
  }
  inline IterationOutput& operator=(IterationOutput&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const IterationOutput& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const IterationOutput* internal_default_instance() {
    return reinterpret_cast<const IterationOutput*>(
               &_IterationOutput_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(IterationOutput& a, IterationOutput& b) {
    a.Swap(&b);
  }
  inline void Swap(IterationOutput* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline IterationOutput* New() const final {
    return CreateMaybeMessage<IterationOutput>(nullptr);
  }

  IterationOutput* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<IterationOutput>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const IterationOutput& from);
  void MergeFrom(const IterationOutput& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(IterationOutput* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "IterationOutput";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_output_2eproto);
    return ::descriptor_table_output_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAllocationsFieldNumber = 1,
    kUniquevaluesFieldNumber = 2,
  };
  // repeated int32 allocations = 1;
  int allocations_size() const;
  private:
  int _internal_allocations_size() const;
  public:
  void clear_allocations();
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_allocations(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
      _internal_allocations() const;
  void _internal_add_allocations(::PROTOBUF_NAMESPACE_ID::int32 value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
      _internal_mutable_allocations();
  public:
  ::PROTOBUF_NAMESPACE_ID::int32 allocations(int index) const;
  void set_allocations(int index, ::PROTOBUF_NAMESPACE_ID::int32 value);
  void add_allocations(::PROTOBUF_NAMESPACE_ID::int32 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
      allocations() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
      mutable_allocations();

  // repeated .UniqueValues uniquevalues = 2;
  int uniquevalues_size() const;
  private:
  int _internal_uniquevalues_size() const;
  public:
  void clear_uniquevalues();
  ::UniqueValues* mutable_uniquevalues(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::UniqueValues >*
      mutable_uniquevalues();
  private:
  const ::UniqueValues& _internal_uniquevalues(int index) const;
  ::UniqueValues* _internal_add_uniquevalues();
  public:
  const ::UniqueValues& uniquevalues(int index) const;
  ::UniqueValues* add_uniquevalues();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::UniqueValues >&
      uniquevalues() const;

  // @@protoc_insertion_point(class_scope:IterationOutput)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 > allocations_;
  mutable std::atomic<int> _allocations_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::UniqueValues > uniquevalues_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_output_2eproto;
};
// -------------------------------------------------------------------

class ChainOutput :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ChainOutput) */ {
 public:
  ChainOutput();
  virtual ~ChainOutput();

  ChainOutput(const ChainOutput& from);
  ChainOutput(ChainOutput&& from) noexcept
    : ChainOutput() {
    *this = ::std::move(from);
  }

  inline ChainOutput& operator=(const ChainOutput& from) {
    CopyFrom(from);
    return *this;
  }
  inline ChainOutput& operator=(ChainOutput&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ChainOutput& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ChainOutput* internal_default_instance() {
    return reinterpret_cast<const ChainOutput*>(
               &_ChainOutput_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(ChainOutput& a, ChainOutput& b) {
    a.Swap(&b);
  }
  inline void Swap(ChainOutput* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ChainOutput* New() const final {
    return CreateMaybeMessage<ChainOutput>(nullptr);
  }

  ChainOutput* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ChainOutput>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ChainOutput& from);
  void MergeFrom(const ChainOutput& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ChainOutput* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ChainOutput";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_output_2eproto);
    return ::descriptor_table_output_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kChainFieldNumber = 1,
  };
  // repeated .IterationOutput chain = 1;
  int chain_size() const;
  private:
  int _internal_chain_size() const;
  public:
  void clear_chain();
  ::IterationOutput* mutable_chain(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::IterationOutput >*
      mutable_chain();
  private:
  const ::IterationOutput& _internal_chain(int index) const;
  ::IterationOutput* _internal_add_chain();
  public:
  const ::IterationOutput& chain(int index) const;
  ::IterationOutput* add_chain();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::IterationOutput >&
      chain() const;

  // @@protoc_insertion_point(class_scope:ChainOutput)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::IterationOutput > chain_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_output_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Par_Row

// repeated double elems = 1;
inline int Par_Row::_internal_elems_size() const {
  return elems_.size();
}
inline int Par_Row::elems_size() const {
  return _internal_elems_size();
}
inline void Par_Row::clear_elems() {
  elems_.Clear();
}
inline double Par_Row::_internal_elems(int index) const {
  return elems_.Get(index);
}
inline double Par_Row::elems(int index) const {
  // @@protoc_insertion_point(field_get:Par_Row.elems)
  return _internal_elems(index);
}
inline void Par_Row::set_elems(int index, double value) {
  elems_.Set(index, value);
  // @@protoc_insertion_point(field_set:Par_Row.elems)
}
inline void Par_Row::_internal_add_elems(double value) {
  elems_.Add(value);
}
inline void Par_Row::add_elems(double value) {
  _internal_add_elems(value);
  // @@protoc_insertion_point(field_add:Par_Row.elems)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
Par_Row::_internal_elems() const {
  return elems_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
Par_Row::elems() const {
  // @@protoc_insertion_point(field_list:Par_Row.elems)
  return _internal_elems();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
Par_Row::_internal_mutable_elems() {
  return &elems_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
Par_Row::mutable_elems() {
  // @@protoc_insertion_point(field_mutable_list:Par_Row.elems)
  return _internal_mutable_elems();
}

// -------------------------------------------------------------------

// Param

// repeated .Par_Row par_rows = 1;
inline int Param::_internal_par_rows_size() const {
  return par_rows_.size();
}
inline int Param::par_rows_size() const {
  return _internal_par_rows_size();
}
inline void Param::clear_par_rows() {
  par_rows_.Clear();
}
inline ::Par_Row* Param::mutable_par_rows(int index) {
  // @@protoc_insertion_point(field_mutable:Param.par_rows)
  return par_rows_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Par_Row >*
Param::mutable_par_rows() {
  // @@protoc_insertion_point(field_mutable_list:Param.par_rows)
  return &par_rows_;
}
inline const ::Par_Row& Param::_internal_par_rows(int index) const {
  return par_rows_.Get(index);
}
inline const ::Par_Row& Param::par_rows(int index) const {
  // @@protoc_insertion_point(field_get:Param.par_rows)
  return _internal_par_rows(index);
}
inline ::Par_Row* Param::_internal_add_par_rows() {
  return par_rows_.Add();
}
inline ::Par_Row* Param::add_par_rows() {
  // @@protoc_insertion_point(field_add:Param.par_rows)
  return _internal_add_par_rows();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Par_Row >&
Param::par_rows() const {
  // @@protoc_insertion_point(field_list:Param.par_rows)
  return par_rows_;
}

// -------------------------------------------------------------------

// UniqueValues

// repeated .Param params = 1;
inline int UniqueValues::_internal_params_size() const {
  return params_.size();
}
inline int UniqueValues::params_size() const {
  return _internal_params_size();
}
inline void UniqueValues::clear_params() {
  params_.Clear();
}
inline ::Param* UniqueValues::mutable_params(int index) {
  // @@protoc_insertion_point(field_mutable:UniqueValues.params)
  return params_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Param >*
UniqueValues::mutable_params() {
  // @@protoc_insertion_point(field_mutable_list:UniqueValues.params)
  return &params_;
}
inline const ::Param& UniqueValues::_internal_params(int index) const {
  return params_.Get(index);
}
inline const ::Param& UniqueValues::params(int index) const {
  // @@protoc_insertion_point(field_get:UniqueValues.params)
  return _internal_params(index);
}
inline ::Param* UniqueValues::_internal_add_params() {
  return params_.Add();
}
inline ::Param* UniqueValues::add_params() {
  // @@protoc_insertion_point(field_add:UniqueValues.params)
  return _internal_add_params();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Param >&
UniqueValues::params() const {
  // @@protoc_insertion_point(field_list:UniqueValues.params)
  return params_;
}

// -------------------------------------------------------------------

// IterationOutput

// repeated int32 allocations = 1;
inline int IterationOutput::_internal_allocations_size() const {
  return allocations_.size();
}
inline int IterationOutput::allocations_size() const {
  return _internal_allocations_size();
}
inline void IterationOutput::clear_allocations() {
  allocations_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::int32 IterationOutput::_internal_allocations(int index) const {
  return allocations_.Get(index);
}
inline ::PROTOBUF_NAMESPACE_ID::int32 IterationOutput::allocations(int index) const {
  // @@protoc_insertion_point(field_get:IterationOutput.allocations)
  return _internal_allocations(index);
}
inline void IterationOutput::set_allocations(int index, ::PROTOBUF_NAMESPACE_ID::int32 value) {
  allocations_.Set(index, value);
  // @@protoc_insertion_point(field_set:IterationOutput.allocations)
}
inline void IterationOutput::_internal_add_allocations(::PROTOBUF_NAMESPACE_ID::int32 value) {
  allocations_.Add(value);
}
inline void IterationOutput::add_allocations(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_add_allocations(value);
  // @@protoc_insertion_point(field_add:IterationOutput.allocations)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
IterationOutput::_internal_allocations() const {
  return allocations_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
IterationOutput::allocations() const {
  // @@protoc_insertion_point(field_list:IterationOutput.allocations)
  return _internal_allocations();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
IterationOutput::_internal_mutable_allocations() {
  return &allocations_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
IterationOutput::mutable_allocations() {
  // @@protoc_insertion_point(field_mutable_list:IterationOutput.allocations)
  return _internal_mutable_allocations();
}

// repeated .UniqueValues uniquevalues = 2;
inline int IterationOutput::_internal_uniquevalues_size() const {
  return uniquevalues_.size();
}
inline int IterationOutput::uniquevalues_size() const {
  return _internal_uniquevalues_size();
}
inline void IterationOutput::clear_uniquevalues() {
  uniquevalues_.Clear();
}
inline ::UniqueValues* IterationOutput::mutable_uniquevalues(int index) {
  // @@protoc_insertion_point(field_mutable:IterationOutput.uniquevalues)
  return uniquevalues_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::UniqueValues >*
IterationOutput::mutable_uniquevalues() {
  // @@protoc_insertion_point(field_mutable_list:IterationOutput.uniquevalues)
  return &uniquevalues_;
}
inline const ::UniqueValues& IterationOutput::_internal_uniquevalues(int index) const {
  return uniquevalues_.Get(index);
}
inline const ::UniqueValues& IterationOutput::uniquevalues(int index) const {
  // @@protoc_insertion_point(field_get:IterationOutput.uniquevalues)
  return _internal_uniquevalues(index);
}
inline ::UniqueValues* IterationOutput::_internal_add_uniquevalues() {
  return uniquevalues_.Add();
}
inline ::UniqueValues* IterationOutput::add_uniquevalues() {
  // @@protoc_insertion_point(field_add:IterationOutput.uniquevalues)
  return _internal_add_uniquevalues();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::UniqueValues >&
IterationOutput::uniquevalues() const {
  // @@protoc_insertion_point(field_list:IterationOutput.uniquevalues)
  return uniquevalues_;
}

// -------------------------------------------------------------------

// ChainOutput

// repeated .IterationOutput chain = 1;
inline int ChainOutput::_internal_chain_size() const {
  return chain_.size();
}
inline int ChainOutput::chain_size() const {
  return _internal_chain_size();
}
inline void ChainOutput::clear_chain() {
  chain_.Clear();
}
inline ::IterationOutput* ChainOutput::mutable_chain(int index) {
  // @@protoc_insertion_point(field_mutable:ChainOutput.chain)
  return chain_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::IterationOutput >*
ChainOutput::mutable_chain() {
  // @@protoc_insertion_point(field_mutable_list:ChainOutput.chain)
  return &chain_;
}
inline const ::IterationOutput& ChainOutput::_internal_chain(int index) const {
  return chain_.Get(index);
}
inline const ::IterationOutput& ChainOutput::chain(int index) const {
  // @@protoc_insertion_point(field_get:ChainOutput.chain)
  return _internal_chain(index);
}
inline ::IterationOutput* ChainOutput::_internal_add_chain() {
  return chain_.Add();
}
inline ::IterationOutput* ChainOutput::add_chain() {
  // @@protoc_insertion_point(field_add:ChainOutput.chain)
  return _internal_add_chain();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::IterationOutput >&
ChainOutput::chain() const {
  // @@protoc_insertion_point(field_list:ChainOutput.chain)
  return chain_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_output_2eproto
